<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("spam.csv")
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df.shape

(5572, 2)

<h3>Train test split</h3>

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size=0.2, random_state=9)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
X_test

51      A gram usually runs like  &lt;#&gt; , a half e...
1470    7 wonders in My WORLD 7th You 6th Ur style 5th...
4564    Come around  &lt;DECIMAL&gt; pm vikky..i'm ots...
1854    I just made some payments so dont have that mu...
3272    You have 1 new voicemail. Please call 08719181...
                              ...
1275    Let me know how to contact you. I've you settl...
287                                                  Ok..
2529                     jay says he'll put in  &lt;#&gt;
779     Happy New year my dear brother. I really do mi...
1195                                        Ok... C ya...
Name: Message, Length: 1115, dtype: object

In [12]:
X_train

2036        Simply sitting and watching match in office..
3516                     I'm job profile seems like bpo..
3134                            So no messages. Had food?
4280    URGENT. Important information for 02 user. Tod...
5       FreeMsg Hey there darling it's been 3 week's n...
                              ...
5014    Uncle G, just checking up on you. Do have a re...
1787    Do you know why god created gap between your f...
501     Fighting with the world is easy, u either win ...
4444    You know my old Dom I told you about yesterday...
382     Yeah sure, give me a couple minutes to track d...
Name: Message, Length: 4457, dtype: object

In [13]:
type(y_train)

pandas.core.series.Series

In [14]:
X_train.values

array(['Simply sitting and watching match in office..',
       "I'm job profile seems like bpo..", 'So no messages. Had food?',
       ...,
       'Fighting with the world is easy, u either win or lose bt fightng with some1 who is close to u is dificult if u lose - u lose if u win - u still lose.',
       'You know my old Dom I told you about yesterday ? His name is Roger? He got in touch with me last night and wants me to meet him today at 2 pm',
       'Yeah sure, give me a couple minutes to track down my wallet'],
      dtype=object)

<h3>Create bag of words representation using CountVectorizer</h3>

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()

In [18]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]

emails_cv = vec.fit_transform(emails)
emails_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 6)>

In [19]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]])

In [20]:
vec.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [21]:
pd.DataFrame(emails_cv.toarray(), columns=vec.get_feature_names_out())

   20  discount  hey  mohan  reward  upto
0   1         1    0      0       1     1
1   0         1    1      1       0     1

In [22]:
vec = CountVectorizer()

X_train_cv = vec.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59064 stored elements and shape (4457, 7765)>

In [23]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
X_train_cv.shape

(4457, 7765)

In [25]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [26]:
vec.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'èn', '〨ud'], dtype=object)

In [27]:
pd.DataFrame(X_train_cv.toarray(), columns=vec.get_feature_names_out())

,00,000,000pes,008704050406,0089,0121,01223585334,0125698789,02,0207,...,zebra,zed,zeros,zindgi,zoe,zogtorius,zoom,zyada,èn,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
vec.vocabulary_

{'simply': 6184,
 'sitting': 6207,
 'and': 959,
 'watching': 7420,
 'match': 4376,
 'in': 3635,
 'office': 4908,
 'job': 3827,
 'profile': 5457,
 'seems': 6008,
 'like': 4112,
 'bpo': 1472,
 'so': 6294,
 'no': 4796,
 'messages': 4454,
 'had': 3288,
 'food': 2927,
 'urgent': 7214,
 'important': 3624,
 'information': 3668,
 'for': 2935,
 '02': 8,
 'user': 7233,
 'today': 6947,
 'is': 3743,
 'your': 7730,
 'lucky': 4256,
 'day': 2169,
 'find': 2851,
 'out': 5013,
 'why': 7523,
 'log': 4178,
 'onto': 4953,
 'http': 3534,
 'www': 7664,
 'urawinner': 7211,
 'com': 1899,
 'there': 6837,
 'fantastic': 2771,
 'surprise': 6643,
 'awaiting': 1159,
 'you': 7726,
 'freemsg': 2984,
 'hey': 3416,
 'darling': 2155,
 'it': 3754,
 'been': 1287,
 'week': 7455,
 'now': 4848,
 'word': 7614,
 'back': 1190,
 'some': 6307,
 'fun': 3036,
 'up': 7194,
 'still': 6498,
 'tb': 6732,
 'ok': 4922,
 'xxx': 7679,
 'std': 6478,
 'chgs': 1774,
 'to': 6941,
 'send': 6028,
 '50': 532,
 'rcv': 5605,
 'also': 925,
 'north': 4828,
 'carolina': 1668,
 'texas': 6791,
 'atm': 1116,
 'would': 7637,
 'just': 3873,
 'go': 3158,
 'the': 6821,
 'gre': 3225,
 'site': 6203,
 'pay': 5125,
 'test': 6787,
 'results': 5778,
 'be': 1265,
 'sent': 6036,
 'aight': 878,
 'do': 2363,
 'want': 7394,
 'get': 3112,
 'money': 4566,
 'private': 5433,
 '2003': 343,
 'account': 786,
 'statement': 6469,
 '07753741225': 31,
 'shows': 6148,
 '800': 632,
 'un': 7139,
 'redeemed': 5671,
 'points': 5295,
 'call': 1608,
 '08715203677': 124,
 'identifier': 3589,
 'code': 1878,
 '42478': 480,
 'expires': 2716,
 '24': 357,
 '10': 253,
 '04': 15,
 'free': 2977,
 'msg': 4615,
 'single': 6192,
 'partner': 5099,
 'area': 1048,
 '1000s': 256,
 'of': 4898,
 'real': 5620,
 'people': 5153,
 'are': 1047,
 'waiting': 7372,
 'chat': 1745,
 '62220cncl': 573,
 'stopcs': 6513,
 '08717890890': 136,
 'per': 5155,
 'eh': 2540,
 'wrongly': 7654,
 'lar': 4016,
 'if': 3594,
 'ready': 5619,
 'horny': 3497,
 'live': 4153,
 'town': 7010,
 'love': 4226,
 'sex': 6059,
 'games': 3062,
 'netcollex': 4746,
 'ltd': 4250,
 '08700621170150p': 74,
 'reply': 5738,
 'stop': 6509,
 'end': 2579,
 'will': 7539,
 'see': 6001,
 'half': 3299,
 'an': 956,
 'hour': 3511,
 'sorry': 6342,
 'll': 4160,
 'later': 4027,
 'eastenders': 2505,
 'tv': 7095,
 'quiz': 5552,
 'what': 7494,
 'flower': 2901,
 'does': 2374,
 'dot': 2412,
 'compare': 1922,
 'herself': 3411,
 'violet': 7311,
 'tulip': 7086,
 'lily': 4118,
 'txt': 7106,
 'or': 4981,
 '84025': 669,
 'chance': 1722,
 'win': 7542,
 '100': 254,
 'cash': 1677,
 'wkent': 7579,
 '150p16': 304,
 'sing': 6189,
 'hu': 3535,
 'think': 6851,
 'its': 3762,
 'someone': 6311,
 'female': 2810,
 'that': 6818,
 'know': 3957,
 'place': 5234,
 'well': 7471,
 'preferably': 5385,
 'citizen': 1816,
 'smart': 6255,
 'help': 3395,
 'navigate': 4715,
 'through': 6877,
 'even': 2655,
 'things': 6850,
 'choosing': 1801,
 'phone': 5194,
 'plan': 5239,
 'require': 5746,
 'guidance': 3267,
 'when': 7499,
 'doubt': 2417,
 'ask': 1088,
 'especially': 2640,
 'girls': 3137,
 'noice': 4802,
 'text': 6793,
 'me': 4404,
 're': 5609,
 'here': 3407,
 'how': 3518,
 'doing': 2387,
 'hope': 3486,
 've': 7273,
 'settled': 6055,
 'new': 4759,
 'school': 5959,
 'year': 7701,
 'wishin': 7564,
 'gr8': 3206,
 'don': 2396,
 'da': 2132,
 'whats': 7496,
 'going': 3170,
 'sleep': 6230,
 'can': 1632,
 'meet': 4421,
 'her': 3406,
 'jamster': 3782,
 'wallpaper': 7384,
 'heart': 3375,
 '88888': 705,
 'apply': 1024,
 '16': 313,
 'only': 4951,
 'need': 4728,
 '08701213186': 75,
 'hack': 3287,
 'backdoor': 1191,
 'entry': 2616,
 'into': 3710,
 '121': 281,
 'rooms': 5842,
 'at': 1109,
 'fraction': 2968,
 'cost': 2020,
 'neo69': 4743,
 '09050280520': 171,
 'subscribe': 6576,
 '25p': 365,
 'pm': 5270,
 'dps': 2428,
 'bcm': 1257,
 'box': 1453,
 '8027': 641,
 'ldn': 4048,
 'wc1n3xx': 7432,
 'rofl': 5829,
 'true': 7060,
 'name': 4686,
 'quit': 5549,
 'soon': 6333,
 'xuhui': 7676,
 'working': 7619,
 'till': 6903,
 'month': 4575,
 'wow': 7641,
 'right': 5802,
 'didn': 2294,
 'mean': 4406,
 'guess': 3262,
 'once': 4943,
 'gave': 3082,
 'on': 4939,
 'boston': 1440,
 'men': 4439,
 'changed': 1725,
 'my': 4667,
 'search': 5985,
 'location': 4172,
 'nyc': 4873,
 'something': 6317,
 'cuz': 2127,
 'signin': 6174,
 'page': 5059,
 'says': 5948,
 'taste': 6717,
 'fish': 2866,
 'curry': 2114,
 'sweet': 6660,
 'dreams': 2438,
 'reverse': 5789,
 'cheating': 1752,
 'not': 4834,
 'mathematics': 4382,
 'ringtone': 5811,
 'club': 1854,
 'polys': 5309,
 'direct': 2326,
 'mobile': 4539,
 'every': 2661,
 'slaaaaave': 6226,
 'where': 7503,
 'must': 4658,
 'summon': 6613,
 'all': 910,
 'time': 6905,
 'wish': 7561,
 'come': 1904,
 'own': 5045,
 'anymore': 995,
 'cartoon': 1675,
 'listening': 4145,
 'music': 4656,
 'amp': 949,
 'eve': 2653,
 'temple': 6769,
 'church': 1812,
 'about': 758,
 'good': 3181,
 'luck': 4254,
 'draw': 2435,
 'takes': 6694,
 '28th': 372,
 'feb': 2797,
 '06': 20,
 'removal': 5718,
 '87239': 694,
 'customer': 2117,
 'services': 6049,
 '08708034412': 94,
 'cutie': 2125,
 'goes': 3166,
 'wales': 7375,
 'kinda': 3937,
 'hills': 3426,
 'shit': 6109,
 'but': 1576,
 'avent': 1151,
 'killed': 3932,
 'myself': 4672,
 'having': 3355,
 'great': 3226,
 'nah': 4680,
 'he': 3360,
 'usf': 7235,
 'lives': 4157,
 'around': 1065,
 'though': 6868,
 '85233': 678,
 'tells': 6762,
 '09066358152': 222,
 'claim': 1820,
 '5000': 534,
 'prize': 5436,
 'have': 3349,
 'enter': 2605,
 'ur': 7210,
 'personal': 5171,
 'details': 2264,
 'prompts': 5473,
 'careful': 1661,
 'length': 4077,
 'same': 5911,
 'top': 6987,
 'shorter': 6131,
 'got': 3196,
 'fringe': 3005,
 'thk': 6859,
 'liao': 4092,
 'too': 6978,
 'lazy': 4044,
 'dun': 2479,
 'wan': 7389,
 'distract': 2349,
 'hello': 3392,
 'wen': 7474,
 'finish': 2856,
 'wrk': 7648,
 'fancy': 2768,
 'meetin': 4422,
 'wiv': 7575,
 'tonite': 6975,
 'as': 1079,
 'break': 1488,
 'from': 3015,
 'dabooks': 2135,
 'did': 2292,
 'hrs': 3531,
 'last': 4022,
 'nite': 4791,
 'told': 6957,
 'him': 3428,
 'returned': 5784,
 'should': 6135,
 'order': 4988,
 'germany': 3111,
 'pence': 5148,
 'minute': 4494,
 'fixed': 2874,
 'line': 4125,
 'via': 7290,
 'access': 775,
 'number': 4861,
 '0844': 63,
 '861': 682,
 '85': 674,
 'prepayment': 5393,
 'lei': 4074,
 'wasn': 7410,
 'enough': 2603,
 'trouble': 7055,
 'sleeping': 6232,
 'goodo': 3189,
 'yes': 7711,
 'we': 7433,
 'speak': 6376,
 'friday': 2995,
 'egg': 2537,
 'potato': 5344,
 'ratio': 5596,
 'tortilla': 6995,
 'needed': 4730,
 'video': 7296,
 'camera': 1628,
 'phones': 5198,
 'with': 7569,
 'price': 5417,
 'rental': 5725,
 '12': 278,
 'mths': 4626,
 '500': 533,
 'cross': 2081,
 'ntwk': 4857,
 'mins': 4491,
 'txts': 7112,
 'mobileupd8': 4543,
 '08001950382': 52,
 'call2optout': 1610,
 '674': 582,
 'mu': 4631,
 'sorting': 6346,
 'our': 5011,
 'narcotics': 4697,
 'situation': 6208,
 'ugh': 7123,
 'leg': 4069,
 'hurts': 3560,
 'musta': 4659,
 'overdid': 5033,
 'mon': 4563,
 'any': 992,
 'plm': 5261,
 'awesome': 1164,
 'remember': 5710,
 'somebody': 6309,
 'high': 3422,
 'first': 2865,
 'diesel': 2298,
 'aiyah': 886,
 'rain': 5567,
 'quite': 5550,
 'big': 1340,
 'leh': 4073,
 'drizzling': 2451,
 'least': 4060,
 'run': 5872,
 'home': 3469,
 'somewhere': 6322,
 'beneath': 1315,
 'pale': 5067,
 'moon': 4579,
 'light': 4109,
 'goodnite': 3187,
 'congratulations': 1963,
 'won': 7598,
 'winner': 7552,
 'august': 1133,
 '1000': 255,
 '09066660100': 236,
 '2309': 356,
 'yetunde': 7716,
 'class': 1827,
 'water': 7421,
 'make': 4324,
 'pls': 5263,
 'dude': 2471,
 'fake': 2753,
 'frnds': 3009,
 'thts': 6885,
 'reffering': 5678,
 'member': 4433,
 'wit': 7568,
 'mail': 4317,
 'link': 4132,
 'vl': 7328,
 'credited': 2070,
 'lt': 4249,
 'gt': 3252,
 'rs': 5854,
 'il': 3602,
 'getiing': 3114,
 'acc': 771,
 'off': 4900,
 'wat': 7415,
 'sdryb8i': 5982,
 'booked': 1425,
 'pilates': 5221,
 'yoga': 7723,
 'lesson': 4084,
 'already': 922,
 'haha': 3291,
 'this': 6858,
 'campus': 1630,
 'library': 4095,
 'take': 6692,
 'part': 5095,
 'wrc': 7642,
 'rally': 5579,
 'oz': 5051,
 'lucozade': 4257,
 'energy': 2588,
 'le': 4050,
 '61200': 572,
 'packs': 5057,
 'co': 1868,
 'uk': 7129,
 'itcould': 3756,
 'has': 3338,
 'everything': 2667,
 'weather': 7440,
 'keep': 3904,
 'extra': 2729,
 'warm': 7401,
 'cold': 1886,
 'nothing': 4838,
 'serious': 6044,
 'lots': 4214,
 'vitamin': 7325,
 'next': 4768,
 'upto': 7208,
 'more': 4581,
 'calls': 1622,
 'standard': 6453,
 'network': 4751,
 'charge': 1734,
 'activate': 801,
 '9061100010': 719,
 'wire3': 7558,
 'net': 4745,
 '1st4terms': 330,
 'pobox84': 5285,
 'm26': 4280,
 '3uz': 464,
 'min': 4479,
 'mobcudb': 4538,
 'nokia': 4806,
 '3510i': 440,
 'colour': 1897,
 'delivered': 2225,
 'tomorrow': 6966,
 '200': 341,
 'minutes': 4495,
 'camcorder': 1626,
 '08000930705': 50,
 'ard': 1046,
 'lor': 4205,
 'geeeee': 3095,
 'internet': 3705,
 'really': 5629,
 'bad': 1193,
 'dear': 2181,
 'reache': 5611,
 'room': 5838,
 'gotta': 3200,
 'collect': 1891,
 'car': 1651,
 'voucher': 7340,
 'holder': 3461,
 'meal': 4405,
 'us': 7225,
 'use': 7229,
 'following': 2919,
 'pc': 5135,
 'enjoy': 2596,
 'dining': 2320,
 'experiencehttp': 2712,
 'vouch4me': 7339,
 'etlp': 2646,
 'asp': 1096,
 'believe': 1305,
 'incredible': 3649,
 'learn': 4058,
 'truly': 7063,
 'amazing': 935,
 'blow': 1399,
 'mind': 4482,
 'o2fwd': 4880,
 '18p': 318,
 'awarded': 1162,
 '2000': 342,
 'guaranteed': 3256,
 '09061790126': 202,
 'land': 4002,
 '3030': 425,
 'valid': 7256,
 '12hrs': 288,
 '150ppm': 307,
 'asked': 1090,
 'dating': 2165,
 'service': 6048,
 'contact': 1977,
 'cant': 1644,
 'who': 7515,
 '09058091854': 175,
 'revealed': 5788,
 'po': 5272,
 'box385': 1459,
 'm6': 4283,
 '6wu': 605,
 'say': 5944,
 'named': 4689,
 'tampa': 6709,
 'coming': 1909,
 'down': 2420,
 'desires': 2254,
 'doctor': 2370,
 'liver': 4155,
 'bit': 1362,
 'stylish': 6567,
 'hair': 3295,
 'managed': 4336,
 'thats': 6820,
 '07973788240': 43,
 '08715203649': 121,
 '40533': 472,
 '31': 430,
 'never': 4756,
 'answer': 982,
 'texts': 6804,
 'confirm': 1955,
 'deny': 2239,
 'said': 5896,
 'look': 4195,
 'pretty': 5411,
 'wif': 7530,
 'long': 4192,
 'cutting': 2126,
 'short': 6127,
 'read': 5616,
 'shame': 6074,
 'tell': 6759,
 'runs': 5874,
 'blame': 1375,
 'ever': 2660,
 'lifted': 4107,
 'hopes': 3491,
 'offer': 4905,
 'am': 934,
 'approaches': 1030,
 'studying': 6556,
 'anyways': 1004,
 'weekend': 7457,
 'pick': 5207,
 'sister': 6200,
 'placed': 5235,
 'birla': 1356,
 'soft': 6298,
 'realize': 5626,
 '40': 467,
 'years': 7702,
 'thousands': 6871,
 'old': 4933,
 'ladies': 3991,
 'running': 5873,
 'tattoos': 6722,
 'depends': 2243,
 'quality': 5537,
 'type': 7117,
 'boye': 1467,
 'faded': 2742,
 'glory': 3150,
 'then': 6833,
 'ralphs': 5580,
 'maybe': 4399,
 'thank': 6810,
 'monday': 4564,
 'announcement': 974,
 'freephone': 2985,
 '0800': 46,
 '542': 554,
 '0825': 61,
 'meeting': 4423,
 'ge': 3092,
 'tmr': 6935,
 'open': 4961,
 'door': 2406,
 'shop': 6122,
 'drop': 2453,
 'either': 2546,
 '10k': 263,
 '5k': 556,
 'travel': 7033,
 '09064011000': 207,
 'ntt': 4856,
 'cr01327bt': 2049,
 'fixedline': 2875,
 'vary': 7266,
 'requirements': 5748,
 'please': 5255,
 'way': 7430,
 'shade': 6067,
 'stuff': 6558,
 'she': 6087,
 'wonderful': 7602,
 'polyphonic': 5308,
 'tone': 6967,
 'mob': 4537,
 'pt2': 5497,
 '87575': 695,
 '1st': 329,
 'txtin': 7109,
 'friends': 3000,
 '150p': 303,
 'hl': 3443,
 '4info': 516,
 'much': 4633,
 'fights': 2833,
 'was': 7408,
 'princess': 5424,
 'shant': 6079,
 'disturb': 2350,
 'jia': 3821,
 'xxxmobilemovieclub': 7680,
 'credit': 2069,
 'click': 1839,
 'wap': 7399,
 'message': 4452,
 'qjkgighjjgcbl': 5535,
 'accept': 774,
 'one': 4945,
 'begging': 1296,
 'change': 1724,
 'list': 4141,
 'buyers': 1582,
 'hiya': 3442,
 'hlday': 3444,
 'pics': 5211,
 'looked': 4196,
 'horrible': 3498,
 'them': 6830,
 'took': 6979,
 'mo': 4535,
 'hows': 3523,
 'camp': 1629,
 'amrca': 951,
 'thing': 6849,
 'serena': 6042,
 'set': 6051,
 'could': 2028,
 'blake': 1374,
 'address': 815,
 'occurs': 4892,
 'sure': 6637,
 'thought': 6869,
 'reaching': 5613,
 'needs': 4732,
 'bed': 1282,
 'fucking': 3027,
 'dealing': 2179,
 'honeybee': 3476,
 'sweetest': 6661,
 'world': 7622,
 'god': 3164,
 'laughed': 4032,
 'wait': 7369,
 'havnt': 3357,
 'met': 4459,
 'person': 5169,
 'reading': 5618,
 'moral': 4580,
 'crack': 2051,
 'jokes': 3840,
 'gm': 3152,
 'gn': 3154,
 'nice': 4772,
 'impressively': 3632,
 'sensible': 6034,
 'went': 7476,
 'early': 2497,
 'feel': 2800,
 'fine': 2853,
 'boring': 1436,
 'yours': 7734,
 'always': 932,
 'brainy': 1478,
 'stomach': 6503,
 'dunno': 2481,
 'cos': 2018,
 'late': 4024,
 'reach': 5610,
 'they': 6844,
 'inside': 3687,
 'ate': 1110,
 'spageddies': 6367,
 'gals': 3058,
 'laughing': 4033,
 'makes': 4325,
 'most': 4589,
 'happy': 3330,
 'bangbabes': 1214,
 'receive': 5646,
 'download': 2421,
 'content': 1981,
 'goto': 3199,
 'bangb': 1213,
 'menu': 4446,
 'hear': 3371,
 'receipt': 5644,
 'sound': 6352,
 'gd': 3090,
 'let': 4086,
 'bill': 1344,
 'millers': 4475,
 'after': 851,
 'wee': 7453,
 'fffff': 2817,
 'kadeem': 3882,
 'far': 2773,
 'gone': 3178,
 'poyyarikatur': 5356,
 'kolathupalayam': 3965,
 'unjalur': 7175,
 'post': 5337,
 'erode': 2630,
 'dis': 2331,
 'noooooooo': 4818,
 'stress': 6529,
 'life': 4101,
 'fair': 2751,
 'lol': 4186,
 'grins': 3236,
 'babe': 1181,
 'thanks': 6811,
 'thinking': 6853,
 'yup': 7750,
 'song': 6328,
 'bro': 1514,
 'creative': 2067,
 'neva': 4754,
 'check': 1754,
 'review': 5790,
 'online': 4949,
 'alone': 919,
 '09061790121': 200,
 'eerie': 2529,
 'tones': 6968,
 '4u': 526,
 'rply': 5852,
 'title': 6921,
 '8007': 635,
 'eg': 2535,
 'dracula': 2430,
 'titles': 6922,
 'ghost': 3123,
 'addamsfa': 810,
 'munsters': 4648,
 'exorcist': 2706,
 'twilight': 7101,
 'getzed': 3121,
 'pobox36504w45wq': 5281,
 'prin': 5421,
 'okay': 4923,
 'wah': 7362,
 'def': 2208,
 'wont': 7605,
 'terms': 6778,
 'conditions': 1950,
 'planned': 5242,
 'yet': 7714,
 'join': 3835,
 'company': 1921,
 'jan': 3784,
 'happen': 3322,
 'oops': 4960,
 'tms': 6937,
 'widelive': 7529,
 'index': 3654,
 'wml': 7586,
 'id': 3584,
 '820554ad0a1705572711': 651,
 'hep': 3405,
 'immunisation': 3619,
 'nigeria': 4778,
 'er': 2626,
 'limping': 4123,
 'slowly': 6250,
 'followed': 2917,
 'by': 1592,
 'aa': 744,
 'exhaust': 2700,
 'hanging': 3318,
 'cuddle': 2099,
 'hold': 3460,
 'strong': 6541,
 'arms': 1061,
 'bucks': 1540,
 'banks': 1217,
 'fees': 2805,
 'better': 1323,
 'bank': 1216,
 'again': 857,
 'shd': 6086,
 'haf': 3290,
 'pages': 5060,
 'add': 809,
 'figures': 2835,
 'many': 4347,
 'nope': 4819,
 'pump': 5507,
 'petrol': 5180,
 'sam': 5908,
 'eachother': 2494,
 'house': 3514,
 'didnt': 2295,
 'holla': 3465,
 'anybody': 993,
 'haven': 3351,
 'tactful': 6687,
 'alex': 901,
 'anything': 1000,
 'buy': 1580,
 'possible': 5335,
 'teach': 6739,
 'dad': 2136,
 'cancer': 1639,
 'give': 3140,
 'flying': 2909,
 'monkeys': 4570,
 'wot': 7633,
 'certainly': 1711,
 'friend': 2999,
 'mine': 4484,
 'login': 4181,
 'dat': 2160,
 'fetching': 2813,
 'iouri': 3725,
 'story': 6522,
 'ten': 6770,
 'times': 6906,
 'nervous': 4744,
 'oh': 4917,
 'baby': 1184,
 'dont': 2400,
 'pictures': 5214,
 'facebook': 2739,
 'special': 6378,
 'stock': 6500,
 'were': 7479,
 'talking': 6703,
 'rose': 5843,
 'red': 5669,
 'blood': 1396,
 'tis': 6919,
 'including': 3642,
 'poor': 5316,
 'relation': 5697,
 'support': 6631,
 'frnd': 3008,
 'some1': 6308,
 'luvs': 4266,
 'praying': 5378,
 'marry': 4364,
 'try': 7068,
 'attended': 1124,
 'catch': 1685,
 'bus': 1569,
 'frying': 3022,
 'tea': 6738,
 'eating': 2511,
 'mom': 4559,
 'left': 4068,
 'over': 5031,
 'dinner': 2321,
 'may': 4397,
 'upgrade': 7200,
 'sim': 6181,
 'card': 1652,
 'loyalty': 4244,
 '0845': 66,
 '021': 13,
 '3680': 443,
 'ends': 2585,
 '28thfeb': 373,
 'aiyo': 888,
 'eat': 2508,
 'bathe': 1241,
 'lover': 4231,
 'kitty': 3950,
 'shaved': 6084,
 'natural': 4709,
 'basically': 1235,
 'lately': 4025,
 'drugs': 2459,
 'obviously': 4888,
 'because': 1276,
 'cool': 2004,
 'college': 1895,
 'tkts': 6928,
 'euro2004': 2649,
 'cup': 2107,
 ...}

In [30]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
np.where(X_train_np[0]!=0)

(array([ 959, 3635, 4376, 4908, 6184, 6207, 7420]),)

In [32]:
X_train_np[0][1771]

np.int64(0)

<h3>Train the naive bayes model</h3>

In [33]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

<h3>Evaluate Performance</h3>

In [34]:
X_test_cv = vec.transform(X_test)

In [35]:
X_test_cv.toarray().shape

(1115, 7765)

In [36]:
model.score(X_test_cv, y_test)

0.9802690582959641

In [37]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.98      0.99      0.99       961
        spam       0.96      0.90      0.93       154

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [38]:
emails = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Hey mohan, can we get together to watch footbal game tomorrow?'
]

In [39]:
emails_count = vec.transform(emails)
emails_count.toarray().shape

(2, 7765)

In [41]:
#emails_count.toarray().shape
model.predict(emails_count)

array(['spam', 'ham'], dtype='<U4')

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [42]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [43]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [44]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.98      0.99      0.99       961
        spam       0.96      0.90      0.93       154

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115